name: web
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: 1.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  intl: ^0.20.2
  provider: ^6.1.5+1
  flutter_bloc: ^9.1.1  # <-- هذا السطر هو الحل، أضفه الآن
  equatable: ^2.0.8
  shared_preferences: 2.2.1   # no ^ — exact version


dependency_overrides:
  shared_preferences_web: 2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_staggered_grid_view: ^0.7.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/