spring.application.name=Backend

spring.datasource.url=jdbc:mysql://localhost:3306/talento
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=4a8f2e1b9d3c7f6a0e5b8d2c4f9a1e3b7d6c0f2a8e4b1d9c3f7a5e0b2d6c8f1
jwt.expiration=900000
jwt.refresh-expiration=2592000000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Readable Hibernate SQL logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# AWS S3
aws.region=${AWS_REGION}
aws.s3.bucket=${S3_BUCKET_NAME}

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

ai.base-url=${AI_BASE_URL}
