<<<<<<< HEAD
spring.application.name=Backend

spring.datasource.url=jdbc:mysql://localhost:3306/talento
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
=======
spring.application.name=Backend

spring.datasource.url=jdbc:mysql://localhost:3306/talento
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh-expiration=2592000000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
>>>>>>> 1fa9b86a49e02d460f12550142ed08adf9cf170e
